version: '3'

services:
  db:
    image: postgres:15.1-alpine
    container_name: verifier-service
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_psw
      - POSTGRES_DB=verifier-service-db
    ports:
      - "5435:5432"